version: 2
jobs:
    build-and-test-chameleon:
        docker:
            - image: circleci/node:10.15.0
        working_directory: ~/chameleon
        steps:
            - checkout
            - restore_cache:
                name: Restore node_modules from cache
                keys:
                  - v3-dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install Node.js dependencies
                command: npm i
            - save_cache:
                name: Save node_modules to cache
                key: v3-dependency-cache-{{ checksum "package.json" }}
                paths:
                  - node_modules/
            - run:
                name: Run all the tests!
                command: npm test
            - persist_to_workspace:
                root: ~/chameleon
                paths:
                  - .deploy/
                  - node_modules/
                  - templates/
                  - assets/
                  - src/
                  - package.json


    deploy-chameleon-dev:
        docker:
            - image: govau/cf-cli
        steps:
            - attach_workspace:
                at: ~/chameleon
            - run:
                name: Deploy to cloud.gov.au development
                command: |
                    cd ~/chameleon
                    mv .deploy/manifest-dev.yml .
                    rm -rf node_modules # Node.js buildpack is stupid see: https://github.com/cloudfoundry/nodejs-buildpack/issues/75
                    cf login -a $CF_API_DEV -o $CF_ORG -s $CF_SPACE -u $CF_USER_DEV -p $CF_PASSWORD_STAGING
                    cf zero-downtime-push chameleon -f manifest-dev.yml


    deploy-chameleon-prod:
        docker:
            - image: govau/cf-cli
        steps:
            - attach_workspace:
                at: ~/chameleon
            - run:
                name: Deploy to cloud.gov.au production
                command: |
                    cd ~/chameleon
                    mv .deploy/manifest-prod.yml .
                    rm -rf node_modules # Node.js buildpack is stupid, see: https://github.com/cloudfoundry/nodejs-buildpack/issues/75
                    cf login -a $CF_API_PROD -o $CF_ORG -s $CF_SPACE -u $CF_USER_PROD -p $CF_PASSWORD_PROD
                    cf zero-downtime-push chameleon -f manifest-prod.yml

workflows:
  version: 2
  build-and-deploy-chameleon:
    jobs:
      - build-and-test-chameleon
      - deploy-chameleon-dev:
          requires:
            - build-and-test-chameleon
          filters:
            branches:
              only: develop
      - deploy-chameleon-prod:
          requires:
            - build-and-test-chameleon
          filters:
            branches:
              only: master